### ISSUE TITLE
Portability of the Consul platform

### ISSUE THREAD

**Issue by taitus** [rockandror/consul#18]
### Description

_Module 6: Analysis and Development of the Portability of the Consul platform_
> Definition of the sections of the platform that are likely to have to be adapted when it is installed in a different city council from Madrid, with the idea that they could be
> configurable by parameters through a web panel.

To achieve the objective of this requirement:
 - Restructuring Settings
   - [x] Move current Settings to new design (#19 )
   - [x] Move Secrets to Settings (#20 )
   - [x] Move Configuration Variables to Settings (#21 )
 - New Installation Wizard (#22 )
