### ISSUE TITLE
Create custom verification process

### ISSUE THREAD

**Issue by taitus** [rockandror/consul#24]
### Why is this Needed?
In order to be able to configure in a simple and clear way the verification system of each installation of Consul.

### Description
- [ ] New data structure for managing verification fields #25 
- [ ] Verification process: Census SOAP #31 
- [ ] Verification process: Census Local #32 
- [ ] Verification process: Phone by SMS #33 
- [ ] Verification process: Custom Verification #34 
- [ ] Verification process: Define order fields #35 

### Current Behavior
Currently there is no custom verification process

### Expected Behavior
In these screenshots we can see all steps of verification process Wizard, but in this issue only develop Census Soap process, Census Local process, Phone by SMS process and Custom Verification process:
https://drive.google.com/drive/folders/1_h46EF9zHU3PM1Hr3WUBhOVDvI5ISBz8?usp=sharing
