### ISSUE TITLE
Create the verification process Wizard

### ISSUE THREAD

**Issue by taitus** [rockandror/consul#29]
### Why is this Needed?
In order to be able to configure in a simple and clear way the verification system of each installation of Consul.

### Description
- [ ] Include access to new "verification process Wizard" to "Application Wizard" Section created on #22 
- [ ] Create styles and templates for Wizard
- [ ] Create a verification process Wizard
  The steps are as follows:
    - [ ] Start Wizard
    - [ ] Verification Process
      - Add 2 options to check: "Personalized Verification Process" and "Without Verification Process". We need create new settings to save value when check "Personalized Verification Process" and need update `Setting[“skip_verification”]` when check "Without Verification" on this step.       
    - [ ] Verification Methods
      - Add 4 modules to enable/disable (Census SOAP, Census Local, Phone by SMS, Custom Verification). We need create 4 new settings to save enable/disable value on this step.    
    - [ ] Census SOAP (#31 ) to Wizard
    - [ ] Census Local (#32 ) to Wizard
    - [ ] Phone by SMS (#33 ) to Wizard
    - [ ] Custom Verification (#34 to Wizard)
    - [ ] Verification fields order (#35 to Wizard)
    - [ ] Finish Wizard 

### Current Behavior
Currently there is no verification process Wizard

### Expected Behavior
In these screenshots we can see all steps of verification process Wizard:
https://drive.google.com/drive/folders/1_h46EF9zHU3PM1Hr3WUBhOVDvI5ISBz8?usp=sharing
